import Head from 'next/head'
import { Inter } from 'next/font/google'
import Counter from '@/components/Counter'
import { useSelector } from 'react-redux'

const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <div className=' my-10 text-right mx-20'>
          <button className=' bg-cyan-700 text-white px-8 py-2'>Add New Counter</button>
        </div>
        <div>
          <Counter title='Match-1' />
        </div>
      </main>
    </>
  )
}
